// NOTE: This is not generated file, and should never to be generated by script.

use crate::*;

pub const IP_LIST: &'static [IpAddr] = &[
    // Cloudflare DNS
    IpAddr::V4(Ipv4Addr::new(1, 0, 0, 1)), // 1.0.0.1
    //IpAddr::V4(Ipv4Addr::new(1, 1, 1, 1)), // 1.1.1.1 [Disabled: Some of LAN located in China is non-standard use this IP as gateway address.
    IpAddr::V6(Ipv6Addr::new(0x2606, 0x4700, 0x4700, 0x0000, 0x0000, 0x0000, 0x0000, 0x1001)), // 2606:4700:4700::1001
    IpAddr::V6(Ipv6Addr::new(0x2606, 0x4700, 0x4700, 0x0000, 0x0000, 0x0000, 0x0000, 0x1111)), // 2606:4700:4700::1111

    // Google DNS
    IpAddr::V4(Ipv4Addr::new(8, 8, 8, 8)), // 8.8.8.8
    IpAddr::V4(Ipv4Addr::new(8, 8, 4, 4)), // 8.8.4.4
    IpAddr::V6(Ipv6Addr::new(0x2001, 0x4860, 0x4860, 0x0000, 0x0000, 0x0000, 0x0000, 0x8888)), // 2001:4860:4860::8888
    IpAddr::V6(Ipv6Addr::new(0x2001, 0x4860, 0x4860, 0x0000, 0x0000, 0x0000, 0x0000, 0x8844)), // 2001:4860:4860::8844

    // Quad9 DNS
    IpAddr::V4(Ipv4Addr::new(9, 9, 9, 10)), // 9.9.9.10
    IpAddr::V4(Ipv4Addr::new(149, 112, 112, 10)), // 149.112.112.10
    IpAddr::V6(Ipv6Addr::new(0x2620, 0x00fe, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0010)), // 2620:fe::10
    IpAddr::V6(Ipv6Addr::new(0x2620, 0x00fe, 0x0000, 0x0000, 0x0000, 0x0000, 0x00fe, 0x0010)), // 2620:fe::fe:10

    // Adguard DNS
    IpAddr::V4(Ipv4Addr::new(94, 140, 14, 140)), // 94.140.14.140
    IpAddr::V4(Ipv4Addr::new(94, 140, 14, 141)), // 94.140.14.141
    IpAddr::V6(Ipv6Addr::new(0x2a10, 0x50c0, 0x0000, 0x0000, 0x0000, 0x0000, 0x0001, 0x00ff)), // 2a10:50c0::1:ff
    IpAddr::V6(Ipv6Addr::new(0x2a10, 0x50c0, 0x0000, 0x0000, 0x0000, 0x0000, 0x0002, 0x00ff)), // 2a10:50c0::2:ff

    // OpenDNS
    IpAddr::V4(Ipv4Addr::new(208, 67, 222, 222)), // 208.67.222.222
    IpAddr::V4(Ipv4Addr::new(208, 67, 220, 220)), // 208.67.220.220
    IpAddr::V6(Ipv6Addr::new(0x2620, 0x0119, 0x0053, 0x0000, 0x0000, 0x0000, 0x0000, 0x0053)), // 2620:119:53::53
    IpAddr::V6(Ipv6Addr::new(0x2620, 0x0119, 0x0035, 0x0000, 0x0000, 0x0000, 0x0000, 0x0035)), // 2620:119:35::35

    // Yandex DNS
    IpAddr::V4(Ipv4Addr::new(77, 88, 8, 8)), // 77.88.8.8
    IpAddr::V4(Ipv4Addr::new(77, 88, 8, 1)), // 77.88.8.1

    // Comodo DNS
    IpAddr::V4(Ipv4Addr::new(8, 26, 56, 26)), // 8.26.56.26
    IpAddr::V4(Ipv4Addr::new(8, 20, 247, 20)), // 8.20.247.20

    // Level 3 Parent DNS
    IpAddr::V4(Ipv4Addr::new(4, 2, 2, 1)), // 4.2.2.1
    IpAddr::V4(Ipv4Addr::new(4, 2, 2, 2)), // 4.2.2.2
    IpAddr::V4(Ipv4Addr::new(4, 2, 2, 3)), // 4.2.2.3
    IpAddr::V4(Ipv4Addr::new(4, 2, 2, 4)), // 4.2.2.4
    IpAddr::V4(Ipv4Addr::new(4, 2, 2, 5)), // 4.2.2.5
    IpAddr::V4(Ipv4Addr::new(4, 2, 2, 6)), // 4.2.2.6

    // Freenom DNS
    IpAddr::V4(Ipv4Addr::new(80, 80, 80, 80)), // 80.80.80.80
    IpAddr::V4(Ipv4Addr::new(80, 80, 81, 81)), // 80.80.81.81
];

