// NOTE: This is not generated file, and should never to be generated by script.

use crate::*;

pub const IP_LIST: &'static [IpAddr] = &[
    // Alibaba DNS [Disabled: 20 QPS per IP]
    /*
    IpAddr::V4(Ipv4Addr::new(223, 5, 5, 5)), // 223.5.5.5
    IpAddr::V4(Ipv4Addr::new(223, 6, 6, 6)), // 223.6.6.6
    */

    // This also Alibaba DNS [20 QPS per IP], but due to rarely IPv6 DNS inside GFW, so this is not disabled.
    IpAddr::V6(Ipv6Addr::new(0x2400, 0x3200, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0001)), // 2400:3200::1
    IpAddr::V6(Ipv6Addr::new(0x2400, 0x3200, 0xbaba, 0x0000, 0x0000, 0x0000, 0x0000, 0x0001)), // 2400:3200:baba::1

    // CNNIC DNS [Disabled: No Response if SOA with blocked domains]
    /*
    IpAddr::V4(Ipv4Addr::new(1, 2, 4, 8)), // 1.2.4.8
    IpAddr::V4(Ipv4Addr::new(210, 2, 4, 8)), // 210.2.4.8
    */

    // 114 DNS
    IpAddr::V4(Ipv4Addr::new(114, 114, 114, 114)), // 114.114.114.114
    IpAddr::V4(Ipv4Addr::new(114, 114, 115, 115)), // 114.114.115.115

    // Tencent DNSPod DNS [20 QPS per domain]
    IpAddr::V4(Ipv4Addr::new(119, 29, 29, 29)), // 119.29.29.29
    IpAddr::V4(Ipv4Addr::new(119, 28, 28, 28)), // 119.28.28.28
    IpAddr::V6(Ipv6Addr::new(0x2402, 0x4e00, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000)), // 2402:4e00::
    IpAddr::V6(Ipv6Addr::new(0x2402, 0x4e00, 0x0001, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000)), // 2402:4e00:1::

    // Baidu DNS [Disabled: long response time (~800ms) if SOA with blocked domains]
    /*
    IpAddr::V4(Ipv4Addr::new(180, 76, 76, 76)), // 180.76.76.76
    */

    // 360 DNS
    IpAddr::V4(Ipv4Addr::new(101, 226, 4, 6)), // 180.76.76.76
    IpAddr::V4(Ipv4Addr::new(218, 30, 118, 6)), // 218.30.118.6
    IpAddr::V4(Ipv4Addr::new(123, 125, 81, 6)), // 123.125.81.6
    IpAddr::V4(Ipv4Addr::new(140, 207, 198, 6)), // 140.207.198.6

    // China Telecom DNS
    IpAddr::V4(Ipv4Addr::new(118, 118, 118, 118)), // 118.118.118.118

    // ByteDance TrafficRoute DNS
    IpAddr::V4(Ipv4Addr::new(180, 184, 1, 1)), // 180.184.1.1
    IpAddr::V4(Ipv4Addr::new(180, 184, 2, 2)), // 180.184.2.2

    // Unknown DNS
    /*
    IpAddr::V4(Ipv4Addr::new(123, 123, 123, 123)),
    IpAddr::V4(Ipv4Addr::new(202, 112, 35, 203)),
    IpAddr::V4(Ipv4Addr::new(221, 224, 200, 54)),
    IpAddr::V4(Ipv4Addr::new(210, 5, 56, 145)),
    IpAddr::V4(Ipv4Addr::new(218, 93, 26, 250)),
    IpAddr::V4(Ipv4Addr::new(182, 254, 116, 116)),
    IpAddr::V4(Ipv4Addr::new(218, 92, 205, 30)),
    IpAddr::V4(Ipv4Addr::new(218, 93, 124, 186)),
    IpAddr::V4(Ipv4Addr::new(210, 5, 56, 146)),
    */
];

